# Generated by Django 3.2.3 on 2021-05-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_price_price_price_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='timelimitsforappeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=150)),
                ('timelimitsforappeal_photo', models.ImageField(upload_to='timelimitsforappeal/')),
                ('times1', models.DateField()),
            ],
        ),
    ]
