# Generated by Django 3.2.3 on 2021-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_timelimitsforappeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsAndObligations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('RightsAndObligations_photo', models.ImageField(upload_to='RightsAndObligations/')),
                ('times', models.DateField()),
            ],
        ),
    ]
