# Generated by Django 3.2.3 on 2021-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_proceduresonewindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAndMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('WorkAndMeeting_photo', models.FileField(upload_to='WorkAndMeeting.html/')),
                ('times', models.DateField()),
            ],
        ),
    ]
