# Generated by Django 3.2.3 on 2021-05-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_leadership_beltop_leadership_minenergo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Videos_video', models.FileField(upload_to='Videos/')),
                ('times', models.DateField()),
            ],
        ),
    ]
