# Generated by Django 3.2.3 on 2021-05-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Absence_notice_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_cylinder_acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_cylinder_acceptance_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_financing_construction_and_installation_works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_financing_construction_and_installation_works_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_funding_design_and_survey_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_funding_design_and_survey_work_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_issuance_of_a_certificate_of_payments_for_consumed_natural_gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_issuance_of_a_certificate_of_payments_for_consumed_natural_gas_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_liquidation_of_the_registered_IBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_liquidation_of_the_registered_IBU_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_payment_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_registration_of_a_discount_on_payment_for_consumed_gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_registration_of_a_discount_on_payment_for_consumed_gas_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_the_reconstruction_of_the_gas_supply_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_the_reconstruction_of_the_gas_supply_system_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application_for_TU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Application_for_TU_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Excavation_permit_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Excavation_permit_application_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Extension_Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Extension_Statement_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gas_startup_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Gas_startup_application_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Large_family_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Large_family_statement_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Liquefied_Petroleum_Gas_Supply_Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Liquefied_Petroleum_Gas_Supply_Statement_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recalculation_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Recalculation_statement_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Sidebar_application_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement_for_the_reconstruction_of_the_gas_supply_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Statement_for_the_reconstruction_of_the_gas_supply_system_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement_on_the_consolidation_of_personal_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Statement_on_the_consolidation_of_personal_accounts_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Statements_for_writing_off_penalties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Statements_for_writing_off_penalties_doc', models.FileField(upload_to='Forms/')),
                ('times', models.DateField()),
            ],
        ),
    ]
