# Generated by Django 3.2.3 on 2021-09-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_command_decree_directive_law_order_other_ruling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Other_doc', models.FileField(upload_to='Services/')),
                ('times', models.DateField()),
            ],
        ),
    ]
