# Generated by Django 3.2.3 on 2021-09-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Other_doc',
            new_name='Services_doc',
        ),
    ]
