# Generated by Django 3.2.3 on 2021-09-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_other_doc_services_services_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership_Shumilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Leadership_Shumilino_photo', models.FileField(upload_to='Leadership_Shumilino/')),
                ('times', models.DateField()),
            ],
        ),
    ]
