# Generated by Django 4.1.4 on 2022-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_gas_potreb'),
    ]

    operations = [
        migrations.CreateModel(
            name='prikaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('prikaz_doc', models.FileField(upload_to='prikaz/')),
                ('times', models.DateField()),
            ],
        ),
    ]
