# Generated by Django 4.1.3 on 2022-12-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_gazification_metan_stroy_gaz_stroy_vvod_your_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Test_doc', models.FileField(upload_to='test/')),
                ('times', models.DateField()),
            ],
        ),
    ]
